/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project2;

import bitcamp.project2.command.TodoCommand;
import bitcamp.project2.util.Prompt;

public class App {

    static String[] menus = new String[]{"리스트 추가", "리스트 상세", "체크 하기 ", "리스트 편집"};

    TodoCommand todoCommand = new TodoCommand();

    public static void main(String[] args) {
        new App().execute();
    }

    void execute() {

        Prompt.close();
    }

    boolean isValidateMenu(int menuNo, String[] menus) {
        return menuNo >= 1 && menuNo <= menus.length;
    }

    String getMenuTitle(int menuNo, String[] menus) {
        return isValidateMenu(menuNo, menus) ? menus[menuNo - 1] : null;
    }
}
